# countries will be set when the server is requested at root for the first time.

# in app, first registered user will be super & admin
User.create(username: "super", email: "super@users.com", password: "123", super: true, admin: true) # super & admin
User.create(username: "admin", email: "admin@users.com", password: "123", admin: true) # not super, just admin
User.create(username: "user", email: "user@users.com", password: "123") # normal user

Post.create(title: "Full-Day Essential Seoul Tour", youtube: "https://youtu.be/3P1CnWI62Ik", content: "Tour the buzzing metropolis of Seoul, South Korea's capital, without any hiccups. On this full-day sightseeing tour with entrance fees included, cross the city in air-conditioned comfort with your guide. Take in top attractions including Gyeongbok Palace, Gwanghwamun Gate, and Jogye Temple, and step back in time at the historic Bukchon Hanok Village. There is also an option to add a second day to tour the DMZ (not in Seoul). [https://www.tripadvisor.com/AttractionProductReview-g294197-d11478953-Full_Day_Essential_Seoul_Tour-Seoul.html]", country_id: 117, user_id: 1)
Post.create(title: "NYC City of Cities", youtube: "https://youtu.be/JCYJj3t9RuU", content: "New York in One Day Guided Sightseeing Tour. Combine New York City’s top attractions in a guided tour via bus and boat (April–December). With insider commentary from your guide, visit Rockefeller Center, South Street Seaport, 9/11 Memorial, and Wall Street. Take a harbor cruise via luxury boat, with views of Ellis Island, the Statue of Liberty, and Brooklyn Bridge. Back on land, hit Lincoln Center and Central Park before wrapping up this whirlwind tour.", country_id: 230, user_id: 2)
Post.create(title: "Ilsan, International Flower Festival", youtube: "https://youtu.be/6aDFBeWqkMk", content: "Ilsan New Town refers to a planned city occupying Ilsandong-gu and Ilsanseo-gu of Goyang. Ilsan is located northwest of Seoul. Like other satellite cities in the Seoul National Capital Area such as Bundang, Ilsan was planned in order to alleviate housing shortages in the city of Seoul. Ilsan has experienced phenomenal growth in the past 15 years, usually drawing in younger generations of upper middle-class and upper-class Koreans. [https://en.wikipedia.org/wiki/Ilsan]", country_id: 117, user_id: 3)
Post.create(title: "Dallas: Everything is big in Texas!!!", youtube: "https://youtu.be/BF55_ykAAYw", content: "Get your bags packed and your road maps ready – the State Fair of Texas® is just around the corner, bringing you an all-access pass to Texas-sized fun! A celebration of all things Texan, the State Fair encourages visitors to explore the great Lone Star State and all it has to offer. A combination of entertainment, art, agriculture, history and cuisine, the State Fair provides fairgoers with a unique way to experience every aspect of Texas culture, all in one place. With that in mind, the State Fair invites you to grab your family and friends and start planning your trip. [https://www.visitdallas.com/things-to-do/venue/view/7538/State-Fair-of-Texas.html]", country_id: 230, user_id: 1)
Post.create(title: "Little Rock, Capital City of Natural State", youtube: "https://youtu.be/yTK16LC6WXE", content: "Little Rock, the capital of Arkansas, is a city on the Arkansas River. It’s home to the William J. Clinton Presidential Library and Museum, with exhibits including a replica of the Oval Office and presidential artifacts. In an 1800s Greek Revival building, the Old State House Museum traces Arkansas history. MacArthur Park has a pond, plus the Arkansas Arts Center, known for its large collection of drawings. ― Google", country_id: 230, user_id: 2)
Post.create(title: "London, England", youtube: "https://youtu.be/gs-skMbz9vo", content: "London, the capital of England and the United Kingdom, is a 21st-century city with history stretching back to Roman times. At its centre stand the imposing Houses of Parliament, the iconic ‘Big Ben’ clock tower and Westminster Abbey, site of British monarch coronations. Across the Thames River, the London Eye observation wheel provides panoramic views of the South Bank cultural complex, and the entire city. ― Google", country_id: 229, user_id: 1)
Post.create(title: "Edinburgh, Scotland", youtube: "https://youtu.be/SRNyfBRhq0A", content: "Edinburgh is Scotland's compact, hilly capital. It has a medieval Old Town and elegant Georgian New Town with gardens and neoclassical buildings. Looming over the city is Edinburgh Castle, home to Scotland’s crown jewels and the Stone of Destiny, used in the coronation of Scottish rulers. Arthur’s Seat is an imposing peak in Holyrood Park with sweeping views, and Calton Hill is topped with monuments and memorials. ― Google", country_id: 229, user_id: 2)
Post.create(title: "Sydney Opera House", youtube: "https://youtu.be/Yc7r_bbt00M", content: "Sydney, capital of New South Wales and one of Australia's largest cities, is best known for its harbourfront Sydney Opera House, with a distinctive sail-like design. Massive Darling Harbour and the smaller Circular Quay port are hubs of waterside life, with the arched Harbour Bridge and esteemed Royal Botanic Garden nearby. Sydney Tower’s outdoor platform, the Skywalk, offers 360-degree views of the city and suburbs. ― Google", country_id: 14, user_id: 3)

Comment.create(content: "I want to visit!", post_id: 1, commenter_id: 2)
Comment.create(content: "you should!!!", post_id: 1, commenter_id: 1)
Comment.create(content: "i live here~ lol", post_id: 2, commenter_id: 3)
Comment.create(content: "enjoy your life there!", post_id: 2, commenter_id: 2)
Comment.create(content: "beautiful~", post_id: 3, commenter_id: 1)
Comment.create(content: "true~~~", post_id: 3, commenter_id: 2)
Comment.create(content: "interesting~", post_id: 4, commenter_id: 3)
Comment.create(content: "maybe next year~", post_id: 1, commenter_id: 2)
Comment.create(content: "great idea~√", post_id: 1, commenter_id: 1)
Comment.create(content: "looks peaceful", post_id: 5, commenter_id: 1)
